#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy this Docker Compose file in production environments.
#--------------------------------------------------------------------------

# Sets the project name.
# name: localhost-databases

# The Docker services.
services:
  # The RabbitMQ container.
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "${RB_CONTAINER_NAME:-rabbitmq}"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    # If healthcheck required
    # healthcheck:
    #   test: [
    #     "CMD", "pg_isready", "-q",
    #     "-d", "${DB_DATABASE:-local}",
    #     "-U", "${DB_USERNAME}"
    #   ]
    #   retries: 3
    #   timeout: 5s
    # if network required
    networks:
      - "${RB_NETWORK_NAME:-rabbitmq_net}"
    # Map the container exposed port to the host port.
    ports:
     - ${RB_PORT:-5672}:5672
     - ${RB_MAN_PORT:-15672}:15672
    volumes:
      - "${RB_VOLUME_DATA_NAME:-rabbitmq_data}:/var/lib/rabbitmq"

# The Docker networks.
networks:
  rabbitmq_net:
    driver: "bridge"

# The Docker volumes.
volumes:
  rabbitmq_data:
    driver: "local"
    name: "${RB_VOLUME_DATA_NAME:-rabbitmq_data}"
